#!/bin/bash
# Copyright 2012 Twitter, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Wrapper around Pig that does the following:
#
# - Inserts our custom pig build into the classpath
# - Adds Ambrose to the classpath
# - Starts Pig with the PigStatsDataVizCollector
#

function log() { echo "$@" >&2; }
function die() { log "$@"; exit 1; }

# test for presence of pig command
which pig >/dev/null 2>&1 || die $(cat <<'EOF'

Command 'pig' not found. This script requires a local installation of Apache
Pig. Please ensure $PIG_HOME/bin is in your $PATH.

EOF
)

# configure default args
AMBROSE_HOME="${AMBROSE_HOME:-$(dirname "$0")/..}"
AMBROSE_PORT="${AMBROSE_PORT:-8080}"
AMBROSE_TIMEOUT="${AMBROSE_TIMEOUT:-600}" # 10 min

# configure paths
export PIG_CLASSPATH=\
$(find "$AMBROSE_HOME/lib" -name '*.jar' -exec printf '%s:' '{}' '+')\
"$PIG_CLASSPATH"
export HADOOP_USER_CLASSPATH_FIRST="true"

# configure the ambrose pig notification listener and port
export PIG_OPTS="\
-Dpig.notification.listener=com.twitter.ambrose.pig.EmbeddedAmbrosePigProgressNotificationListener \
-Dambrose.port=$AMBROSE_PORT \
-Dambrose.post.script.sleep.seconds=$AMBROSE_TIMEOUT \
$PIG_OPTS"

# construct pig command line, log and invoke
log "PIG_CLASSPATH=$PIG_CLASSPATH"
log "PIG_OPTS=$PIG_OPTS"
exec pig $@
